### ISSUE TITLE
reshapeExt breaks on R v3.4 +

### ISSUE THREAD

**Issue by jbadham** [alexkowa/sparkTable#22]
I have some existing code to create a sparkTable that worked in R v3.3. When I upgraded to 3.5, I was getting an error in the `reshapeExt` to prepare the sparkTable objects. I tracked it back and the internal call to `reshape` is generating the error. It can be seen with this code:

```
testdf <- data.frame(type = c("A", "A", "A", "B", "B", "B"),
                     rank = c(1, 2, 3, 1, 2, 3),
                     val1 = c(2, 5, 7, 2, 8, 5),
                     val2 = c(3, 8, 6, 7, 3, 4))

testdflong <- reshape(testdf,
                      idvar = "type",
                      timevar = "rank",
                      varying = list(3,4),
                      direction = "long")

testdflong <- reshapeExt(testdf,
                      idvar = "type",
                      timevar = "rank",
                      varying = list(3,4))

```

which generates the error:

> Error in `row.names<-.data.frame`(`*tmp*`, value = paste(ids, times[i],  : 
>   duplicate 'row.names' are not allowed
> In addition: Warning message:
> non-unique values when setting 'row.names': ‘A.1’, ‘B.1’

Checking with various friends, this error is generated from v3.4 (Windows and Mac). In the event, I got round the problem by simply adding the `attributes` to the dataframe so that it registered as being in `long` format for the purposes of sparkTable.

**Comment by alexkowa** [comment]
I think it should look like:
```
testdflong <- reshapeExt(testdf,
                         idvar = c("rank","type"), varying = list(3,4),timevar=NULL
                         )
```

**Comment by jbadham** [comment]
Hi. Yes, that corrected the problem on the real dataset too. Not sure why the code worked on previous versions of R, but it is now fine. Sorry it took so long to confirm, I have been out of the country and didn't have access to the original dataset and code.
