### ISSUE TITLE
can't use sparkTable because of proxy working from R 3.4

### ISSUE THREAD

**Issue by moodymudskipper** [alexkowa/sparkTable#23]
I'm stuck with an older version of R (3.3.1) and `sparkTable` depends on proxy which is available only from 3.4. Is a hard dependency on proxy absolutely necessary ?

Package description says :

> Provides an extensible framework for the efficient calculation of auto- and crossproximities,
> along with implementations of the most popular ones.

Which seems like something that might not be necessary for sparkTable's basic features ?

Is there a way for me to hack my way round it ? I'd love to make use of sparkTable.

**Comment by alexkowa** [comment]
I removed the dependency to statMatch (which itself depends on proxy).
`install_github("alexkowa/sparkTable")`

**Comment by moodymudskipper** [comment]
Fantastic, thanks!
