### ISSUE TITLE
Request to update package supporting R Version 4.2.2.

### ISSUE THREAD

**Issue by yurisong1** [alexkowa/sparkTable#24]
Hi Alex, 

Warning in install.packages :
  package ‘sparkTable’ is not available for this version of R

R version used was 4.2.2. Is there any plan of updating the package and continue supporting?

**Comment by alexkowa** [comment]
We archived this package more than 2 years ago, so we do not have any intention to further develop it. Feel free to fork it and use/adapt it as you see fit.
